# Generated by Django 3.2.7 on 2022-01-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mask',
            name='img_url',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
