# Generated by Django 3.2.7 on 2022-01-04 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mask',
            name='details',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='mask',
            name='guide',
            field=models.TextField(max_length=500),
        ),
    ]
